export const packageName = "@node-red-contrib-webapp/schema";

export {
    actionDefinitionSchema,
    actionMessageCommandSchema,
    actionMessageSchema,
    actionParamEntrySchema,
    actionParamListSchema,
    actionParamsSchema,
    actionParamValueTypeSchema,
    actionTargetModeSchema,
    actionToTypeSchema,
    actionTypeSchema,
    navigateTargetModeSchema,
    appModelSchema,
    ALERT_VARIANTS,
    BADGE_VARIANTS,
    bindingSchema,
    leafBindingSchema,
    BUTTON_VARIANTS,
    BUTTON_LINK_MODES,
    COMPONENT_SIZES,
    COMPONENT_VARIANT_DEFAULT,
    COMPONENT_VARIANT_VOCABULARY,
    componentDefinitionSchema,
    componentEventHandlerSchema,
    componentKindSchema,
    CONTAINER_VARIANTS,
    DEFAULT_ICON_LIBRARY,
    iconValueSchema,
    iconFieldSchema,
    normalizeIconValue,
    errorContextSchema,
    errorOriginSchema,
    errorSeveritySchema,
    structuredErrorSchema,
    INPUT_VARIANTS,
    SEVERITY_VARIANTS,
    TEXT_STYLES,
    TEXT_COLOR_VARIANTS,
    dialogDefinitionSchema,
    layoutDefinitionSchema,
    navigationDefinitionSchema,
    queryDefinitionSchema,
    runtimeIntegrationModelSchema,
    slotDefinitionSchema,
    routeDefinitionSchema,
    routeNodePathSchema,
    storeOperationSchema,
    storeDefinitionSchema,
    uiEventMessageSchema,
    uiStoreMessageSchema
} from "./contracts";
export {
    collectMissingStandardLayouts,
    createAppRootRoute,
    getStandardLayoutPresetDefinition,
    isStandardLayoutPreset,
    standardLayoutPresetIds
} from "./layout-presets";
export type {
    ActionDefinition,
    ActionMessage,
    ActionMessageCommand,
    ActionParamEntry,
    ActionParamList,
    ActionParams,
    ActionParamValueType,
    ActionTargetMode,
    ActionToType,
    ActionType,
    NavigateTargetMode,
    AppModel,
    BindingDefinition,
    LeafBindingDefinition,
    ButtonVariant,
    ButtonLinkMode,
    ComponentSize,
    ComponentDefinition,
    ComponentEventHandler,
    ContainerVariant,
    IconValue,
    IconField,
    ErrorContext,
    ErrorOrigin,
    ErrorSeverity,
    StructuredError,
    InputVariant,
    SeverityVariant,
    TextStyle,
    TextColorVariant,
    DialogDefinition,
    LayoutDefinition,
    NavigationDefinition,
    QueryDefinition,
    RuntimeIntegrationModel,
    RouteDefinition,
    SlotDefinition,
    StoreOperation,
    StoreDefinition,
    UiEventMessage,
    UiStoreMessage
} from "./contracts";
export type { StandardLayoutPresetId } from "./layout-presets";

export {
    buildDesignTokenCss,
    DESIGN_TOKEN_CSS_VARS,
    designTokensSchema,
    uiActionNodeDefinitionSchema,
    uiAlertNodeDefinitionSchema,
    uiAppNodeDefinitionSchema,
    uiBadgeNodeDefinitionSchema,
    uiButtonNodeDefinitionSchema,
    uiCheckboxNodeDefinitionSchema,
    uiContainerNodeDefinitionSchema,
    uiDatepickerNodeDefinitionSchema,
    uiDialogNodeDefinitionSchema,
    uiEmptyStateNodeDefinitionSchema,
    uiInputNodeDefinitionSchema,
    uiNavigationNodeDefinitionSchema,
    uiNodeDefinitionSchema,
    uiProgressNodeDefinitionSchema,
    uiQueryNodeDefinitionSchema,
    uiRadioNodeDefinitionSchema,
    uiRouteNodeDefinitionSchema,
    uiSelectNodeDefinitionSchema,
    uiSkeletonNodeDefinitionSchema,
    uiSliderNodeDefinitionSchema,
    uiStoreNodeDefinitionSchema,
    uiSwitchNodeDefinitionSchema,
    uiTableNodeDefinitionSchema,
    uiTextareaNodeDefinitionSchema,
    uiTextNodeDefinitionSchema,
    uiToastNodeDefinitionSchema,
    uiTabsNodeDefinitionSchema,
    uiAccordionNodeDefinitionSchema,
    uiBreadcrumbNodeDefinitionSchema,
    uiMenuNodeDefinitionSchema,
    uiPaginationNodeDefinitionSchema,
    uiStepperNodeDefinitionSchema,
    uiImageNodeDefinitionSchema,
    uiIconNodeDefinitionSchema,
    uiListNodeDefinitionSchema,
    uiAvatarNodeDefinitionSchema,
    uiDividerNodeDefinitionSchema,
    uiLogNodeDefinitionSchema,
    validateUiNodeDefinition
} from "./node-definitions";
export type {
    DesignTokens,
    UiActionNodeDefinition,
    UiAlertNodeDefinition,
    UiAppNodeDefinition,
    UiAvatarNodeDefinition,
    UiBadgeNodeDefinition,
    UiButtonNodeDefinition,
    UiCheckboxNodeDefinition,
    UiContainerNodeDefinition,
    UiDatepickerNodeDefinition,
    UiDialogNodeDefinition,
    UiDividerNodeDefinition,
    UiEmptyStateNodeDefinition,
    UiIconNodeDefinition,
    UiImageNodeDefinition,
    UiInputNodeDefinition,
    UiListNodeDefinition,
    UiLogNodeDefinition,
    UiNavigationNodeDefinition,
    UiNodeDefinition,
    UiProgressNodeDefinition,
    UiQueryNodeDefinition,
    UiRadioNodeDefinition,
    UiRouteNodeDefinition,
    UiSelectNodeDefinition,
    UiSkeletonNodeDefinition,
    UiSliderNodeDefinition,
    UiStoreNodeDefinition,
    UiSwitchNodeDefinition,
    UiTableNodeDefinition,
    UiTextareaNodeDefinition,
    UiTextNodeDefinition,
    UiToastNodeDefinition,
    UiTabsNodeDefinition,
    UiAccordionNodeDefinition,
    UiBreadcrumbNodeDefinition,
    UiMenuNodeDefinition,
    UiPaginationNodeDefinition,
    UiStepperNodeDefinition
} from "./node-definitions";

export {
    formatMountResolutionError,
    formatValidationIssues,
    parseMountReference,
    resolveMountReference,
    validateAppModel,
    validateMountReference
} from "./validation";
export type {
    MountResolution,
    MountScope,
    ParsedMountReference,
    ParsedNamedMountReference,
    ParsedRouteMountReference
} from "./validation";

export {
    customersCrudAppModelFixture,
    customersCrudExampleFlowFixture,
    customersCrudNodeSetFixture,
    customersCrudRuntimeIntegrationFixture,
    fixtureAppModels,
    operationsConsoleAppModelFixture,
    reactiveBindingFixture,
    storeSubPathBindingFixture
} from "./fixtures";
