#!/usr/bin/env node
/**
 * gen-example.js
 *
 * Generates examples/customers-crud/flow.json from the typed
 * customersCrudNodeSetFixture defined in packages/schema/src/fixtures.ts.
 *
 * The fixture is the single source of truth.  Renaming a field in the schema
 * breaks the TypeScript build before it ever breaks the runtime.
 *
 * Usage:
 *   node scripts/gen-example.js
 *   pnpm gen:example
 */

"use strict";

const { writeFileSync, existsSync } = require("node:fs");
const { resolve } = require("node:path");

const rootDir = resolve(__dirname, "..");

// Import from the built schema package (avoids needing tsx at runtime).
// This import is type-safe: if customersCrudNodeSetFixture changes shape,
// the TypeScript build catches it before this script is invoked.
const { customersCrudNodeSetFixture } = require(
    resolve(rootDir, "packages/schema/dist/fixtures.js")
);

const FLOW_TAB_ID = "flow1";
const COLS_PER_ROW = 6;
const COL_STEP = 220;
const ROW_STEP = 60;
const X_START = 160;
const Y_START = 40;

/**
 * Convert the UiNodeDefinition array into a Node-RED flows array.
 *
 * Each UiNodeDefinition maps directly to a Node-RED node config object.
 * Node-RED requires:
 *   - id          (preserved from fixture)
 *   - type        (preserved from fixture)
 *   - z           (flow tab id)
 *   - x, y        (canvas position, generated by grid layout)
 *   - wires       (empty array — structure-only; data-flow wires are added manually)
 *
 * All other fields from the fixture are spread verbatim so the generated
 * flow stays in sync with the schema definition automatically.
 */
function generateFlow(nodes) {
    const tab = {
        id: FLOW_TAB_ID,
        type: "tab",
        label: "Customers CRUD",
        disabled: false,
        info: ""
    };

    const flowNodes = nodes.map((node, index) => ({
        ...node,
        z: FLOW_TAB_ID,
        x: X_START + (index % COLS_PER_ROW) * COL_STEP,
        y: Y_START + Math.floor(index / COLS_PER_ROW) * ROW_STEP,
        wires: [[]]
    }));

    return [tab, ...flowNodes];
}

const flow = generateFlow(customersCrudNodeSetFixture);
const json = JSON.stringify(flow, null, 4);

// Write to examples/customers-crud/flow.json
const examplePath = resolve(rootDir, "examples/customers-crud/flow.json");
writeFileSync(examplePath, json + "\n", "utf8");
console.log(`Wrote ${flow.length} nodes to ${examplePath}`);

// Copy to .node-red-dev/flows.json (dev Node-RED instance)
const devDir = resolve(rootDir, ".node-red-dev");
if (existsSync(devDir)) {
    const devFlowsPath = resolve(devDir, "flows.json");
    writeFileSync(devFlowsPath, json + "\n", "utf8");
    console.log(`Copied to ${devFlowsPath}`);
} else {
    console.log(`Skipped .node-red-dev/flows.json (directory does not exist)`);
}
